-- ⚠️ WARNING: This script resets the destinations and bookings tables to ensure a clean state.
-- It will DELETE existing bookings and destinations.

-- 1. Reset Tables
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS destinations;

-- 2. Create Destinations Table (using bigint to match frontend mock data)
CREATE TABLE destinations (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  country text,
  city text,
  description text,
  price numeric,
  image text,
  rating numeric,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Populate Destinations (matching the frontend Mock Data)
INSERT INTO destinations (name, country, city, description, price, image, rating)
VALUES
('Kyoto', 'Japan', 'Kyoto', 'Kyoto is the cultural capital of Japan...', 150, 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=2070&auto=format&fit=crop', 4.9),
('Maldives', 'Maldives', 'Malé Atoll', 'Experience the ultimate tropical paradise...', 450, 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=2065&auto=format&fit=crop', 5.0),
('Bali', 'Indonesia', 'Ubud', 'Tropical paradise with lush jungles...', 120, 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=2038&auto=format&fit=crop', 4.7),
('Reykjavik', 'Iceland', 'Reykjavik', 'Witness the northern lights...', 250, 'https://images.unsplash.com/photo-1476610182048-b716b8518aae?q=80&w=2159&auto=format&fit=crop', 4.9),
('Santorini', 'Greece', 'Oia', 'Stunning sunsets, white-washed houses...', 300, 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?q=80&w=2072&auto=format&fit=crop', 4.9),
('Bora Bora', 'French Polynesia', 'Vaitape', 'A small South Pacific island...', 800, 'https://images.unsplash.com/photo-1537905569824-f89f14cceb68?q=80&w=1998&auto=format&fit=crop', 4.9),
('Machu Picchu', 'Peru', 'Cusco Region', 'Iconic Incan citadel...', 200, 'https://images.unsplash.com/photo-1526392060635-9d6019884377?q=80&w=2070&auto=format&fit=crop', 4.9),
('New York City', 'USA', 'New York', 'The City That Never Sleeps...', 350, 'https://images.unsplash.com/photo-1496417263034-38ec4f0d6b21?q=80&w=2070&auto=format&fit=crop', 4.7),
('Paris', 'France', 'Paris', 'The City of Light...', 300, 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=2070&auto=format&fit=crop', 4.8);

-- 4. Create Bookings Table
CREATE TABLE bookings (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id uuid NOT NULL, -- Links to auth.users
  destination_id bigint REFERENCES destinations(id), -- Links to destinations
  booking_type text,
  total_price numeric,
  travelers integer,
  start_date date,
  end_date date,
  status text DEFAULT 'pending',
  user_name text,
  user_email text,
  phone text
);

-- 5. Refresh API
NOTIFY pgrst, 'reload config';
