-- Create destinations table
create table if not exists destinations (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  country text,
  city text,
  price numeric,
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table destinations enable row level security;

-- Allow public read access
create policy "Allow public read access" on destinations for select using (true);

-- Allow all access for now (since Admin is frontend-only state)
create policy "Allow full access" on destinations for all using (true) with check (true);

-- Create bookings table
create table if not exists bookings (
  id bigint generated by default as identity primary key,
  user_id uuid, -- linking to auth.users if available, or just store ID
  destination_id bigint references destinations(id),
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table bookings enable row level security;

-- Allow full access
create policy "Allow full access" on bookings for all using (true) with check (true);
